### ISSUE TITLE
TypeError: start=x <class 'float'>

### ISSUE THREAD

**Issue by schorlton-bugseq** [linsalrob/PhiSpy#68]
Thanks for the interesting and useful tool! Hit this error on the following file, running v4.2.21 from bioconda.

```bash
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/035/013/225/GCA_035013225.1_ASM3501322v1/GCA_035013225.1_ASM3501322v1_genomic.gbff.gz

gunzip GCA_035013225.1_ASM3501322v1_genomic.gbff.gz

PhiSpy.py -o test --threads 2 --output_choice 4 GCA_035013225.1_ASM3501322v1_genomic.gbff
```

```bash
PROPHAGE: 1 Contig: JAXAWC010000001.1 Start: 153092 Stop: 185630
There were 5 repeats with the same length as the best. One chosen somewhat randomly!
PROPHAGE: 2 Contig: JAXAWC010000001.1 Start: 713995 Stop: 768336
There were 3 repeats with the same length as the best. One chosen somewhat randomly!
PROPHAGE: 3 Contig: JAXAWC010000001.1 Start: 793493 Stop: 828285
There were 2 repeats with the same length as the best. One chosen somewhat randomly!
PROPHAGE: 4 Contig: JAXAWC010000001.1 Start: 856014 Stop: 878592
PROPHAGE: 5 Contig: JAXAWC010000001.1 Start: 1314389 Stop: 1327077
PROPHAGE: 6 Contig: JAXAWC010000001.1 Start: 1612290 Stop: 1645677
PROPHAGE: 7 Contig: JAXAWC010000002.1 Start: 96167 Stop: 170512
PROPHAGE: 8 Contig: JAXAWC010000002.1 Start: 197841 Stop: 210406
There were 2 repeats with the same length as the best. One chosen somewhat randomly!
PROPHAGE: 9 Contig: JAXAWC010000002.1 Start: 260138 Stop: 282609
There were 2 repeats with the same length as the best. One chosen somewhat randomly!
PROPHAGE: 10 Contig: JAXAWC010000002.1 Start: 297846 Stop: 321813
PROPHAGE: 11 Contig: JAXAWC010000007.1 Start: 44912 Stop: 61286
Creating output files
/opt/conda/envs/test/lib/python3.10/site-packages/Bio/SeqFeature.py:257: BiopythonDeprecationWarning: Using the strand argument is deprecated, and will be removed in a future release. Please set it via the location object instead.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/conda/envs/test/bin/PhiSpy.py", line 10, in <module>
    sys.exit(run())
  File "/opt/conda/envs/test/lib/python3.10/site-packages/PhiSpyModules/main.py", line 122, in run
    main(sys.argv)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/PhiSpyModules/main.py", line 114, in main
    PhiSpyModules.write_all_outputs(**vars(args_parser))
  File "/opt/conda/envs/test/lib/python3.10/site-packages/PhiSpyModules/writers.py", line 326, in
 write_all_outputs
    location=FeatureLocation(self.pp[i]['start'] - 1, self.pp[i]['stop'] - 1),
  File "/opt/conda/envs/test/lib/python3.10/site-packages/Bio/SeqFeature.py", line 1035, in __init__
    raise TypeError(f"start={start!r} {type(start)}")
TypeError: start=1611137.0 <class 'float'>
```

**Comment by lvdongyuan** [comment]
Hello, I m also facing this problem now. It seems that only several gbk files meets this circumstance. Have you solved it?
